# The main entry point of your workflow.
# Run from root dir (parent dir of this Snakefile)
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

# --------------
# Configuration
# --------------
from pathlib import Path
import pandas as pd
import yaml

configfile: "workflow/config/general.yaml"

# --------------
# Load rules
# --------------
include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/meta_analysis.smk"
include: "rules/gcta_cojo.smk"
include: "rules/ldak.smk"
include: "rules/ldsc.smk"
include: "rules/finemap.smk"

# Target output

target_analysis = 'Pheno1_EUR'

rule all:
    input:
        f"results/meta/{target_analysis}/FORMAT-GWAS.tsv.gz",
        f"results/gcta/{target_analysis}/genome-wide_slct-cojo.tsv",
        f"results/ldak/{target_analysis}/bld_ldak.hers",
        f"results/ldsc/{target_analysis}/ldsc_h2.log"
        


